### ISSUE TITLE
Standalone version?

### ISSUE THREAD

**Issue by poVoq** [dimagi/Vellum#1069]
Since the standalone branch is a decade outdated: any chance to have a working stand-alone from the master branch?

Thanks!

**Comment by millerdev** [comment]
That branch is indeed outdated, and probably should be deleted.

Vellum stand-alone mode works quite well from the master branch. Follow the instructions for [running tests in a browser](https://github.com/dimagi/Vellum#running-tests), except after running `npm run testserver` simply load the URL printed in the terminal in your browser.

The terminal output should look something like this:
```
$ npm run testserver

> vellum@1.6.0 testserver /home/dimagi/code/vellum
> `npm bin`/http-server -p ${VELLUM_PORT:-8088}

Starting up http-server, serving ./
Available on:
  http://127.0.0.1:8088       <--------------- load this URL in your browser
Hit CTRL-C to stop the server
```
